---

- name: Enable the ECS agent systemd service and ensure it is not masked
  systemd:
    name: 'docker-container@ecs-agent.service'
    enabled: true
    state: stopped
    masked: false
    daemon_reload: true
