---
# tasks file for ecs-rhel

- name: Prepare | Enable rhel-7-server-rhui-extras-rpms
  ini_file:
    path: /etc/yum.repos.d/redhat-rhui.repo
    #section: rhel-7-server-rhui-extras-rpms
    section: rhui-rhel-7-server-rhui-extras-rpms
    option: enabled
    value: '1'
    mode: '0644'
    backup: false
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == "7"

- name: Install podman
  package:
    name: podman
    state: present

  # ECS agent wants to talk to the daemon using this
- name: Enable Podman Remote API Socket
  systemd:
    name: 'io.podman.socket'
    enabled: true
    state: stopped
    masked: false
    daemon_reload: true

- name: Configure SELinux to allow podman systemd unit files
  seboolean:
    name: container_manage_cgroup
    state: true
    persistent: true

- name: Install firewalld
  package:
    name: firewalld
    state: present

- name: Start firewalld service
  systemd:
    name: firewalld
    enabled: true
    state: started
    masked: false

- name: Enable masquerade
  firewalld:
    masquerade: true
    state: enabled
    permanent: true
    zone: public

- name: Pull ecs agent container image
  podman_image:
    name: 'docker.io/amazon/amazon-ecs-agent' 
    tag: 'latest'
    state: present
    pull: true

- name: Create systemd unit for starting ECS docker agent
  copy:
    src: 'ecs-agent-podman.service'
    dest: '/etc/systemd/system/podman-container@ecs-agent.service'

  # Don't start the service yet. This system could be an AMI template
- name: Enable the ECS agent systemd service and ensure it is not masked
  systemd:
    name: 'podman-container@ecs-agent.service'
    enabled: true
    state: stopped
    masked: false
    daemon_reload: true
