---
# tasks file for ecs-rhel

- name: Prepare | Enable localnet in sysctl
  sysctl:
    name: 'net.ipv4.conf.all.route_localnet'
    value: '1'
    state: present

- name: Prepare | Create ECS config directory
  file:
    name: '/etc/ecs'
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Configure ECS
  template:
    src: 'ecs.config.j2'
    dest: '/etc/ecs/ecs.config'

- name: Install and configure docker
  import_tasks: prepare_docker.yml
  when: ( podman is false )

- name: Install and configure podman
  import_tasks: prepare_podman.yml
  when: ( podman is true )
